<a href="https://colab.research.google.com/github/G-Haripriya10/ADM_2303A51104/blob/main/ADM_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
path = kagglehub.dataset_download("hrdkcodes/wine-data")
print("Path to dataset files:", path)

100%|██████████| 4.31k/4.31k [00:00<00:00, 3.30MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/hrdkcodes/wine-data/versions/1


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
ds=pd.read_csv('/root/.cache/kagglehub/datasets/hrdkcodes/wine-data/versions/1/wine.csv')
x=ds.iloc[:,0:13].values
y=ds.iloc[:,13].values
print(x)
print(y)

[[ 1.   14.23  1.71 ...  5.64  1.04  3.92]
 [ 1.   13.2   1.78 ...  4.38  1.05  3.4 ]
 [ 1.   13.16  2.36 ...  5.68  1.03  3.17]
 ...
 [ 3.   13.27  4.28 ... 10.2   0.59  1.56]
 [ 3.   13.17  2.59 ...  9.3   0.6   1.62]
 [ 3.   14.13  4.1  ...  9.2   0.61  1.6 ]]
[1065 1050 1185 1480  735 1450 1290 1295 1045 1045 1510 1280 1320 1150
 1547 1310 1280 1130 1680  845  780  770 1035 1015  845  830 1195 1285
  915 1035 1285 1515  990 1235 1095  920  880 1105 1020  760  795 1035
 1095  680  885 1080 1065  985 1060 1260 1150 1265 1190 1375 1060 1120
  970 1270 1285  520  680  450  630  420  355  678  502  510  750  718
  870  410  472  985  886  428  392  500  750  463  278  714  630  515
  520  450  495  562  680  625  480  450  495  290  345  937  625  428
  660  406  710  562  438  415  672  315  510  488  312  680  562  325
  607  434  385  407  495  345  372  564  625  465  365  380  380  378
  352  466  342  580  630  530  560  600  650  695  720  515  580  590
  600  780  520  550  855 

In [ ]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.preprocessing import StandardScaler as SS
sc=SS()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=1)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)
explained_variance=pca.explained_variance_ratio_

In [ ]:
from sklearn.linear_model import LogisticRegression as LR
classifier_1=LR(random_state=3)
classifier_1.fit(x_train,y_train)

LogisticRegression(random_state=3)

In [ ]:
y_pred=classifier_1.predict(x_test)
print(y_pred)

[1285  520 1285 1285  680 1035 1285  520  680  625  520  560 1285 1285
  520 1035 1035 1150  520 1285 1285  680 1035  680  520  680  680  680
  630  520 1035 1285  520  680 1285 1285]


In [ ]:
from sklearn.metrics import confusion_matrix as cm
cm=cm(y_test,y_pred)
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
import matplotlib.pyplot as mpltl
mpltl.xlim(x1.min(),x1.max())
mpltl.ylim(x2.min(),x2.max())
for s,t in enumerate(np.unique(y_set)):
    mpltl.scatter(x_set[y_set==t,0],x_set[y_set==t,1],c=LCM(('red','green','blue'))(s),lable=t)

NameError: name 'x1' is not defined